language: go
sudo: false

env:
  global:
    secure: U8z+dkIVizUUUY6ptk2wVmeEcEcjlKIjy2rxk0IEF//IkvBkAusPfOHLyKALKgijaL0zBBbcWv0wbvwCDOf+1RIl85LtBjwjofCdEyw7m31bGVQvz1FTNe/gbJ5IjZmKJ9VxV8HC3hvjj5LQHXZCw+Et/68tcrJNm7dvF7nrM+QNOzPRBRF84sgLZgL6ExYHpzUhCfnlpCZP/Nr/amdoQlZ650V6K+Ew+JtR3I5FyUXZgJYGkWb1LUSl2ViheTV6ncrcBv4bW1gmYVPqEOTVJSYHqFv3g4Bf+I7Sp6D6AN/uyvIErgCEfAkMOLOL8ExIFN3oiznqI8E7vTMtZ2hzHbxlent8g30u8aa4C4mGIwxakJ8d+XhT9YYaTE1/kB5YCkRjAtFoN3PQovabR7rJuoJq0ClCrfsHihHtACreWmDOTAFB1DPbbSb6EscEbjORyz0et736d/sVCMiK7AL0Ho0s1uTDlgWvI9aWoHjfWZKxhSIZiXu3Ygg/Po9nrb6RU+RYWYhQWlf5myYEOIikLjSiYty2SPqH9p/ZdZZzwAFYhMUacW9MHmhNlfHs0Mmb1X18MCB6QDYGI+H8yVcwx7JTQVdv5d2E+x/fTpk5yzMjQsyzvk2Ubesg0o9PzKNiDNEILV5qdfZP+DtkbLi1/Wq7O9UslxdBUGdqHedQraY=

go:
- 1.6
- 1.7
- tip

install:
- go get -t ./...
- curl https://glide.sh/get | sh && glide i

script:
- go test -cover -coverpkg github.com/drgomesp/gogo/generator -coverprofile generator.coverprofile ./generator

after_script:
- gover
- goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
